### ISSUE TITLE
Outdated Appsflyer SDK version

### ISSUE THREAD

**Issue by J0xFlash** [coronalabs/com.coronalabs-plugin.appsflyer#2]
Plugin need to be updated to latest Appsflyer SDK version (6.9.4).
Current SDK version 6.5.3 is outdated (Aug 2022).
Project with the current version of the plugin does not pass the Appsflyer SDK integration test. It does not track non-organic installs.

[There was a similar issue in this thread on this forum a few years ago](https://forums.solar2d.com/t/appsflyer-plugin-has-older-sdk-of-appsflyer/149782)
Плагин необходимо обновить до последней версии Appsflyer SDK (6.9.4).
Текущая версия 6.5.3 устарела (она была выпущена в августе 2022-го).
Проект с текущей версией плагина не проходит тест интеграции в консоли Appsflyer. Он не отслеживает не-органические установки. Скорее всего Appsflyer вообще не принимает от него никаких данных.

[В этой теме на форуме уже сталкивались с такой проблемой несколько лет назад](https://forums.solar2d.com/t/appsflyer-plugin-has-older-sdk-of-appsflyer/149782)

**Comment by J0xFlash** [comment]
@Shchvova @scottrules44 
Look here please

**Comment by J0xFlash** [comment]
@Shchvova @scottrules44
FYI

**Comment by Shchvova** [comment]
please test

**Comment by J0xFlash** [comment]
> please test

Hello @Shchvova , 
Does not work. 2023.3686
After it reaches the plugin declaration, an error occurs. 
`local appsflyer = require( "plugin.appsflyer" )`

**Error:**
```
java.lang.ExceptionInInitializ
erError
```

If you disable the appsflyer require, then the build works correctly
There were no bugs in version 3685. I did not change the code in the project. Just updated the engine to version 3686.

**Comment by Shchvova** [comment]
Ok. Looking into it

**Comment by Shchvova** [comment]
There is something terribly wrong with SDKs after 6.6.0. For now reverted to 6.5.4 while investigationg

**Comment by Shchvova** [comment]
OK. It is good to update to 6.10.1. now

**Comment by J0xFlash** [comment]
Thanks

**Comment by J0xFlash** [comment]
@Shchvova 
Thank you, it worked!
